"""Initial migration: add watch_targets and content_checks tables

Revision ID: 3bd2bbb181c6
Revises: 
Create Date: 2025-12-07 02:02:34.763747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bd2bbb181c6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watch_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('check_interval_seconds', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watch_targets_id'), 'watch_targets', ['id'], unique=False)
    op.create_index(op.f('ix_watch_targets_url'), 'watch_targets', ['url'], unique=True)
    op.create_table('content_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('is_success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('content_body', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('content_changed', sa.Boolean(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('content_length', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['watch_targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_checks_checked_at'), 'content_checks', ['checked_at'], unique=False)
    op.create_index(op.f('ix_content_checks_content_hash'), 'content_checks', ['content_hash'], unique=False)
    op.create_index(op.f('ix_content_checks_id'), 'content_checks', ['id'], unique=False)
    op.create_index(op.f('ix_content_checks_target_id'), 'content_checks', ['target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_checks_target_id'), table_name='content_checks')
    op.drop_index(op.f('ix_content_checks_id'), table_name='content_checks')
    op.drop_index(op.f('ix_content_checks_content_hash'), table_name='content_checks')
    op.drop_index(op.f('ix_content_checks_checked_at'), table_name='content_checks')
    op.drop_table('content_checks')
    op.drop_index(op.f('ix_watch_targets_url'), table_name='watch_targets')
    op.drop_index(op.f('ix_watch_targets_id'), table_name='watch_targets')
    op.drop_table('watch_targets')
    # ### end Alembic commands ###
